/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mug.gltf --transform 
Files: mug.gltf [25.89KB] > mug-transformed.glb [15.84KB] (39%)
Author: LightSwitch (https://sketchfab.com/edwardlewis450)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plain-mug-19c8fe5702b544d0a1409d3dac1cf90e
Title: Plain Mug
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from 'valtio'
import state from "../store"
import { Decal, useTexture } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mug-transformed.glb')
  const snap= useSnapshot(state)
      const logoTexture= useTexture(snap.logoDecal)
    const fullTexture= useTexture(snap.fullDecal)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} >
        {
           snap.isLogoTexture && (
            <Decal
            position={[0.01,0.13,0.18]}
            rotation={[0,0,0]}
            scale={0.15}
            map={logoTexture}
            
           
            
            />)
           }
        
        </mesh>
    </group>
  )
}

useGLTF.preload('/mug-transformed.glb')
